language: ruby
rvm:
  - 1.8.7
  - jruby # 1.9
env:
  - RAILS_VERSION="~> 4.0.0"
  - RAILS_VERSION="~> 3.2.13"
  - RAILS_VERSION="~> 3.0.20"
  - RAILS_VERSION="~> 2.3.18"
matrix:
  exclude:
    - rvm: 1.8.7
      env: RAILS_VERSION="~> 4.0.0"
